//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CookMeModel", "FK_Directions_Recipe", "Recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CookMe.Entities.Recipe), "Directions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CookMe.Entities.Direction), true)]
[assembly: EdmRelationshipAttribute("CookMeModel", "FK_Ingredient_Recipe", "Recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CookMe.Entities.Recipe), "Ingredient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CookMe.Entities.Ingredient), true)]
[assembly: EdmRelationshipAttribute("CookMeModel", "FK_Note_Note", "Recipe", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CookMe.Entities.Recipe), "Note", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CookMe.Entities.Note), true)]

#endregion

namespace CookMe.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CookMeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CookMeEntities object using the connection string found in the 'CookMeEntities' section of the application configuration file.
        /// </summary>
        public CookMeEntities() : base("name=CookMeEntities", "CookMeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CookMeEntities object.
        /// </summary>
        public CookMeEntities(string connectionString) : base(connectionString, "CookMeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CookMeEntities object.
        /// </summary>
        public CookMeEntities(EntityConnection connection) : base(connection, "CookMeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Direction> Directions
        {
            get
            {
                if ((_Directions == null))
                {
                    _Directions = base.CreateObjectSet<Direction>("Directions");
                }
                return _Directions;
            }
        }
        private ObjectSet<Direction> _Directions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ingredient> Ingredients
        {
            get
            {
                if ((_Ingredients == null))
                {
                    _Ingredients = base.CreateObjectSet<Ingredient>("Ingredients");
                }
                return _Ingredients;
            }
        }
        private ObjectSet<Ingredient> _Ingredients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Note> Notes
        {
            get
            {
                if ((_Notes == null))
                {
                    _Notes = base.CreateObjectSet<Note>("Notes");
                }
                return _Notes;
            }
        }
        private ObjectSet<Note> _Notes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Recipe> Recipes
        {
            get
            {
                if ((_Recipes == null))
                {
                    _Recipes = base.CreateObjectSet<Recipe>("Recipes");
                }
                return _Recipes;
            }
        }
        private ObjectSet<Recipe> _Recipes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Directions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDirections(Direction direction)
        {
            base.AddObject("Directions", direction);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ingredients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngredients(Ingredient ingredient)
        {
            base.AddObject("Ingredients", ingredient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Notes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNotes(Note note)
        {
            base.AddObject("Notes", note);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Recipes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRecipes(Recipe recipe)
        {
            base.AddObject("Recipes", recipe);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CookMeModel", Name="Direction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Direction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Direction object.
        /// </summary>
        /// <param name="recipeId">Initial value of the RecipeId property.</param>
        /// <param name="directionId">Initial value of the DirectionId property.</param>
        /// <param name="instruction">Initial value of the Instruction property.</param>
        /// <param name="rank">Initial value of the Rank property.</param>
        public static Direction CreateDirection(global::System.Int32 recipeId, global::System.Int32 directionId, global::System.String instruction, global::System.Int32 rank)
        {
            Direction direction = new Direction();
            direction.RecipeId = recipeId;
            direction.DirectionId = directionId;
            direction.Instruction = instruction;
            direction.Rank = rank;
            return direction;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeId
        {
            get
            {
                return _RecipeId;
            }
            set
            {
                if (_RecipeId != value)
                {
                    OnRecipeIdChanging(value);
                    ReportPropertyChanging("RecipeId");
                    _RecipeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecipeId");
                    OnRecipeIdChanged();
                }
            }
        }
        private global::System.Int32 _RecipeId;
        partial void OnRecipeIdChanging(global::System.Int32 value);
        partial void OnRecipeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DirectionId
        {
            get
            {
                return _DirectionId;
            }
            set
            {
                if (_DirectionId != value)
                {
                    OnDirectionIdChanging(value);
                    ReportPropertyChanging("DirectionId");
                    _DirectionId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DirectionId");
                    OnDirectionIdChanged();
                }
            }
        }
        private global::System.Int32 _DirectionId;
        partial void OnDirectionIdChanging(global::System.Int32 value);
        partial void OnDirectionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Instruction
        {
            get
            {
                return _Instruction;
            }
            set
            {
                OnInstructionChanging(value);
                ReportPropertyChanging("Instruction");
                _Instruction = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Instruction");
                OnInstructionChanged();
            }
        }
        private global::System.String _Instruction;
        partial void OnInstructionChanging(global::System.String value);
        partial void OnInstructionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Rank
        {
            get
            {
                return _Rank;
            }
            set
            {
                OnRankChanging(value);
                ReportPropertyChanging("Rank");
                _Rank = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rank");
                OnRankChanged();
            }
        }
        private global::System.Int32 _Rank;
        partial void OnRankChanging(global::System.Int32 value);
        partial void OnRankChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CookMeModel", "FK_Directions_Recipe", "Recipe")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("CookMeModel.FK_Directions_Recipe", "Recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("CookMeModel.FK_Directions_Recipe", "Recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("CookMeModel.FK_Directions_Recipe", "Recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("CookMeModel.FK_Directions_Recipe", "Recipe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CookMeModel", Name="Ingredient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingredient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ingredient object.
        /// </summary>
        /// <param name="recipeId">Initial value of the RecipeId property.</param>
        /// <param name="ingredientId">Initial value of the IngredientId property.</param>
        /// <param name="quantity">Initial value of the Quantity property.</param>
        /// <param name="measurement">Initial value of the Measurement property.</param>
        /// <param name="ingredientName">Initial value of the IngredientName property.</param>
        /// <param name="preparation">Initial value of the Preparation property.</param>
        public static Ingredient CreateIngredient(global::System.Int32 recipeId, global::System.Int32 ingredientId, global::System.String quantity, global::System.String measurement, global::System.String ingredientName, global::System.String preparation)
        {
            Ingredient ingredient = new Ingredient();
            ingredient.RecipeId = recipeId;
            ingredient.IngredientId = ingredientId;
            ingredient.Quantity = quantity;
            ingredient.Measurement = measurement;
            ingredient.IngredientName = ingredientName;
            ingredient.Preparation = preparation;
            return ingredient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeId
        {
            get
            {
                return _RecipeId;
            }
            set
            {
                if (_RecipeId != value)
                {
                    OnRecipeIdChanging(value);
                    ReportPropertyChanging("RecipeId");
                    _RecipeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecipeId");
                    OnRecipeIdChanged();
                }
            }
        }
        private global::System.Int32 _RecipeId;
        partial void OnRecipeIdChanging(global::System.Int32 value);
        partial void OnRecipeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IngredientId
        {
            get
            {
                return _IngredientId;
            }
            set
            {
                if (_IngredientId != value)
                {
                    OnIngredientIdChanging(value);
                    ReportPropertyChanging("IngredientId");
                    _IngredientId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IngredientId");
                    OnIngredientIdChanged();
                }
            }
        }
        private global::System.Int32 _IngredientId;
        partial void OnIngredientIdChanging(global::System.Int32 value);
        partial void OnIngredientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.String _Quantity;
        partial void OnQuantityChanging(global::System.String value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Measurement
        {
            get
            {
                return _Measurement;
            }
            set
            {
                OnMeasurementChanging(value);
                ReportPropertyChanging("Measurement");
                _Measurement = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Measurement");
                OnMeasurementChanged();
            }
        }
        private global::System.String _Measurement;
        partial void OnMeasurementChanging(global::System.String value);
        partial void OnMeasurementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IngredientName
        {
            get
            {
                return _IngredientName;
            }
            set
            {
                OnIngredientNameChanging(value);
                ReportPropertyChanging("IngredientName");
                _IngredientName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IngredientName");
                OnIngredientNameChanged();
            }
        }
        private global::System.String _IngredientName;
        partial void OnIngredientNameChanging(global::System.String value);
        partial void OnIngredientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Preparation
        {
            get
            {
                return _Preparation;
            }
            set
            {
                OnPreparationChanging(value);
                ReportPropertyChanging("Preparation");
                _Preparation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Preparation");
                OnPreparationChanged();
            }
        }
        private global::System.String _Preparation;
        partial void OnPreparationChanging(global::System.String value);
        partial void OnPreparationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CookMeModel", "FK_Ingredient_Recipe", "Recipe")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("CookMeModel.FK_Ingredient_Recipe", "Recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("CookMeModel.FK_Ingredient_Recipe", "Recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("CookMeModel.FK_Ingredient_Recipe", "Recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("CookMeModel.FK_Ingredient_Recipe", "Recipe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CookMeModel", Name="Note")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Note : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Note object.
        /// </summary>
        /// <param name="recipeId">Initial value of the RecipeId property.</param>
        /// <param name="noteId">Initial value of the NoteId property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        public static Note CreateNote(global::System.Int32 recipeId, global::System.Int32 noteId, global::System.String text, global::System.DateTime dateCreated)
        {
            Note note = new Note();
            note.RecipeId = recipeId;
            note.NoteId = noteId;
            note.Text = text;
            note.DateCreated = dateCreated;
            return note;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeId
        {
            get
            {
                return _RecipeId;
            }
            set
            {
                if (_RecipeId != value)
                {
                    OnRecipeIdChanging(value);
                    ReportPropertyChanging("RecipeId");
                    _RecipeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecipeId");
                    OnRecipeIdChanged();
                }
            }
        }
        private global::System.Int32 _RecipeId;
        partial void OnRecipeIdChanging(global::System.Int32 value);
        partial void OnRecipeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NoteId
        {
            get
            {
                return _NoteId;
            }
            set
            {
                if (_NoteId != value)
                {
                    OnNoteIdChanging(value);
                    ReportPropertyChanging("NoteId");
                    _NoteId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NoteId");
                    OnNoteIdChanged();
                }
            }
        }
        private global::System.Int32 _NoteId;
        partial void OnNoteIdChanging(global::System.Int32 value);
        partial void OnNoteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateModified
        {
            get
            {
                return _DateModified;
            }
            set
            {
                OnDateModifiedChanging(value);
                ReportPropertyChanging("DateModified");
                _DateModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateModified");
                OnDateModifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateModified;
        partial void OnDateModifiedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateModifiedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CookMeModel", "FK_Note_Note", "Recipe")]
        public Recipe Recipe
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("CookMeModel.FK_Note_Note", "Recipe").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("CookMeModel.FK_Note_Note", "Recipe").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Recipe> RecipeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Recipe>("CookMeModel.FK_Note_Note", "Recipe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Recipe>("CookMeModel.FK_Note_Note", "Recipe", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CookMeModel", Name="Recipe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Recipe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Recipe object.
        /// </summary>
        /// <param name="recipeId">Initial value of the RecipeId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="shortTitle">Initial value of the ShortTitle property.</param>
        /// <param name="source">Initial value of the Source property.</param>
        /// <param name="preperationTime">Initial value of the PreperationTime property.</param>
        /// <param name="cookTime">Initial value of the CookTime property.</param>
        /// <param name="rating">Initial value of the Rating property.</param>
        /// <param name="isFavorite">Initial value of the IsFavorite property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        public static Recipe CreateRecipe(global::System.Int32 recipeId, global::System.String title, global::System.String shortTitle, global::System.String source, global::System.Int32 preperationTime, global::System.Int32 cookTime, global::System.Double rating, global::System.Int32 isFavorite, global::System.DateTime dateCreated)
        {
            Recipe recipe = new Recipe();
            recipe.RecipeId = recipeId;
            recipe.Title = title;
            recipe.ShortTitle = shortTitle;
            recipe.Source = source;
            recipe.PreperationTime = preperationTime;
            recipe.CookTime = cookTime;
            recipe.Rating = rating;
            recipe.IsFavorite = isFavorite;
            recipe.DateCreated = dateCreated;
            return recipe;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RecipeId
        {
            get
            {
                return _RecipeId;
            }
            set
            {
                if (_RecipeId != value)
                {
                    OnRecipeIdChanging(value);
                    ReportPropertyChanging("RecipeId");
                    _RecipeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RecipeId");
                    OnRecipeIdChanged();
                }
            }
        }
        private global::System.Int32 _RecipeId;
        partial void OnRecipeIdChanging(global::System.Int32 value);
        partial void OnRecipeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShortTitle
        {
            get
            {
                return _ShortTitle;
            }
            set
            {
                OnShortTitleChanging(value);
                ReportPropertyChanging("ShortTitle");
                _ShortTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShortTitle");
                OnShortTitleChanged();
            }
        }
        private global::System.String _ShortTitle;
        partial void OnShortTitleChanging(global::System.String value);
        partial void OnShortTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Servings
        {
            get
            {
                return _Servings;
            }
            set
            {
                OnServingsChanging(value);
                ReportPropertyChanging("Servings");
                _Servings = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Servings");
                OnServingsChanged();
            }
        }
        private Nullable<global::System.Int32> _Servings;
        partial void OnServingsChanging(Nullable<global::System.Int32> value);
        partial void OnServingsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PreperationTime
        {
            get
            {
                return _PreperationTime;
            }
            set
            {
                OnPreperationTimeChanging(value);
                ReportPropertyChanging("PreperationTime");
                _PreperationTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PreperationTime");
                OnPreperationTimeChanged();
            }
        }
        private global::System.Int32 _PreperationTime;
        partial void OnPreperationTimeChanging(global::System.Int32 value);
        partial void OnPreperationTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CookTime
        {
            get
            {
                return _CookTime;
            }
            set
            {
                OnCookTimeChanging(value);
                ReportPropertyChanging("CookTime");
                _CookTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CookTime");
                OnCookTimeChanged();
            }
        }
        private global::System.Int32 _CookTime;
        partial void OnCookTimeChanging(global::System.Int32 value);
        partial void OnCookTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Rating
        {
            get
            {
                return _Rating;
            }
            set
            {
                OnRatingChanging(value);
                ReportPropertyChanging("Rating");
                _Rating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rating");
                OnRatingChanged();
            }
        }
        private global::System.Double _Rating;
        partial void OnRatingChanging(global::System.Double value);
        partial void OnRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IsFavorite
        {
            get
            {
                return _IsFavorite;
            }
            set
            {
                OnIsFavoriteChanging(value);
                ReportPropertyChanging("IsFavorite");
                _IsFavorite = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFavorite");
                OnIsFavoriteChanged();
            }
        }
        private global::System.Int32 _IsFavorite;
        partial void OnIsFavoriteChanging(global::System.Int32 value);
        partial void OnIsFavoriteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Calories
        {
            get
            {
                return _Calories;
            }
            set
            {
                OnCaloriesChanging(value);
                ReportPropertyChanging("Calories");
                _Calories = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Calories");
                OnCaloriesChanged();
            }
        }
        private Nullable<global::System.Int32> _Calories;
        partial void OnCaloriesChanging(Nullable<global::System.Int32> value);
        partial void OnCaloriesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TotalFat
        {
            get
            {
                return _TotalFat;
            }
            set
            {
                OnTotalFatChanging(value);
                ReportPropertyChanging("TotalFat");
                _TotalFat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalFat");
                OnTotalFatChanged();
            }
        }
        private Nullable<global::System.Int32> _TotalFat;
        partial void OnTotalFatChanging(Nullable<global::System.Int32> value);
        partial void OnTotalFatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SaturatedFat
        {
            get
            {
                return _SaturatedFat;
            }
            set
            {
                OnSaturatedFatChanging(value);
                ReportPropertyChanging("SaturatedFat");
                _SaturatedFat = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SaturatedFat");
                OnSaturatedFatChanged();
            }
        }
        private Nullable<global::System.Int32> _SaturatedFat;
        partial void OnSaturatedFatChanging(Nullable<global::System.Int32> value);
        partial void OnSaturatedFatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Carbohydrates
        {
            get
            {
                return _Carbohydrates;
            }
            set
            {
                OnCarbohydratesChanging(value);
                ReportPropertyChanging("Carbohydrates");
                _Carbohydrates = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Carbohydrates");
                OnCarbohydratesChanged();
            }
        }
        private Nullable<global::System.Int32> _Carbohydrates;
        partial void OnCarbohydratesChanging(Nullable<global::System.Int32> value);
        partial void OnCarbohydratesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Fiber
        {
            get
            {
                return _Fiber;
            }
            set
            {
                OnFiberChanging(value);
                ReportPropertyChanging("Fiber");
                _Fiber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fiber");
                OnFiberChanged();
            }
        }
        private Nullable<global::System.Int32> _Fiber;
        partial void OnFiberChanging(Nullable<global::System.Int32> value);
        partial void OnFiberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Protien
        {
            get
            {
                return _Protien;
            }
            set
            {
                OnProtienChanging(value);
                ReportPropertyChanging("Protien");
                _Protien = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Protien");
                OnProtienChanged();
            }
        }
        private Nullable<global::System.Int32> _Protien;
        partial void OnProtienChanging(Nullable<global::System.Int32> value);
        partial void OnProtienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> VitaminC
        {
            get
            {
                return _VitaminC;
            }
            set
            {
                OnVitaminCChanging(value);
                ReportPropertyChanging("VitaminC");
                _VitaminC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VitaminC");
                OnVitaminCChanged();
            }
        }
        private Nullable<global::System.Int32> _VitaminC;
        partial void OnVitaminCChanging(Nullable<global::System.Int32> value);
        partial void OnVitaminCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Calcium
        {
            get
            {
                return _Calcium;
            }
            set
            {
                OnCalciumChanging(value);
                ReportPropertyChanging("Calcium");
                _Calcium = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Calcium");
                OnCalciumChanged();
            }
        }
        private Nullable<global::System.Int32> _Calcium;
        partial void OnCalciumChanging(Nullable<global::System.Int32> value);
        partial void OnCalciumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                OnDateCreatedChanging(value);
                ReportPropertyChanging("DateCreated");
                _DateCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCreated");
                OnDateCreatedChanged();
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateModified
        {
            get
            {
                return _DateModified;
            }
            set
            {
                OnDateModifiedChanging(value);
                ReportPropertyChanging("DateModified");
                _DateModified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateModified");
                OnDateModifiedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateModified;
        partial void OnDateModifiedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateModifiedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CookMeModel", "FK_Directions_Recipe", "Directions")]
        public EntityCollection<Direction> Directions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Direction>("CookMeModel.FK_Directions_Recipe", "Directions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Direction>("CookMeModel.FK_Directions_Recipe", "Directions", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CookMeModel", "FK_Ingredient_Recipe", "Ingredient")]
        public EntityCollection<Ingredient> Ingredients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ingredient>("CookMeModel.FK_Ingredient_Recipe", "Ingredient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ingredient>("CookMeModel.FK_Ingredient_Recipe", "Ingredient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CookMeModel", "FK_Note_Note", "Note")]
        public EntityCollection<Note> Notes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Note>("CookMeModel.FK_Note_Note", "Note");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Note>("CookMeModel.FK_Note_Note", "Note", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
