//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace TiendaVirtual.Domain
{
    public  partial class Producto
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Nombre
        {
            get;
            set;
        }
    
        public virtual decimal Precio
        {
            get;
            set;
        }
    
        public virtual int CategoriaId
        {
            get { return _categoriaId; }
            set
            {
                if (_categoriaId != value)
                {
                    if (Categoria != null && Categoria.Id != value)
                    {
                        Categoria = null;
                    }
                    _categoriaId = value;
                }
            }
        }
        private int _categoriaId;

        #endregion
        #region Complex Properties
    
        public virtual Imagen Imagen
        {
            get { return _imagen; }
            set { _imagen = value; }
        }
        private Imagen _imagen = new Imagen();

        #endregion
        #region Navigation Properties
    
        public virtual Categoria Categoria
        {
            get { return _categoria; }
            set
            {
                if (!ReferenceEquals(_categoria, value))
                {
                    var previousValue = _categoria;
                    _categoria = value;
                    FixupCategoria(previousValue);
                }
            }
        }
        private Categoria _categoria;

        #endregion
        #region Association Fixup
    
        private void FixupCategoria(Categoria previousValue)
        {
            if (Categoria != null)
            {
                if (CategoriaId != Categoria.Id)
                {
                    CategoriaId = Categoria.Id;
                }
            }
        }

        #endregion
    }
}
