//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ocean.Sql.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ocean.Sql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.  Please contact tech support..
        /// </summary>
        public static string DataAccess_BuildDataAccessException_Operation_failed___Please_contact_tech_support_ {
            get {
                return ResourceManager.GetString("DataAccess_BuildDataAccessException_Operation_failed___Please_contact_tech_suppor" +
                        "t_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record is already in the database..
        /// </summary>
        public static string DataAccess_BuildDataAccessException_Record_is_already_in_the_database_ {
            get {
                return ResourceManager.GetString("DataAccess_BuildDataAccessException_Record_is_already_in_the_database_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was not found..
        /// </summary>
        public static string DataAccess_BuildDataAccessException_The_record_was_not_found_ {
            get {
                return ResourceManager.GetString("DataAccess_BuildDataAccessException_The_record_was_not_found_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record was updated by another user since you selected it.  Please re-edit this record and attempt to save it again..
        /// </summary>
        public static string DataAccess_BuildDataAccessException_The_record_was_updated_by_another_user_since_you_selected_it___Please_re_edit_this_record_and_attempt_to_save_it_again_ {
            get {
                return ResourceManager.GetString("DataAccess_BuildDataAccessException_The_record_was_updated_by_another_user_since_" +
                        "you_selected_it___Please_re_edit_this_record_and_attempt_to_save_it_again_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value not programmed, please see administrator. Value : {0}.
        /// </summary>
        public static string DataAccess_BuildDataAccessException_Value_not_programmed__please_see_administrator__Value____0_FormatString {
            get {
                return ResourceManager.GetString("DataAccess_BuildDataAccessException_Value_not_programmed__please_see_administrato" +
                        "r__Value____0_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method did not receive any command text.  Calling code must supply the command text..
        /// </summary>
        public static string DataAccess_ExecuteScaler_The_method_did_not_receive_any_command_text___Calling_code_must_supply_the_command_text_ {
            get {
                return ResourceManager.GetString("DataAccess_ExecuteScaler_The_method_did_not_receive_any_command_text___Calling_co" +
                        "de_must_supply_the_command_text_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sqlconnection state was {0}.  The method only permits the sqlconnection state to be either open or closed only..
        /// </summary>
        public static string DataAccess_ExecuteScaler_The_sqlconnection_state_was__0____The_method_only_permits_the_sqlconnection_state_to_be_either_open_or_closed_only_FormatString {
            get {
                return ResourceManager.GetString("DataAccess_ExecuteScaler_The_sqlconnection_state_was__0____The_method_only_permit" +
                        "s_the_sqlconnection_state_to_be_either_open_or_closed_only_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method did not receive an instianted dataset, dataset was nothing.  The dataset must be instianted before calling this procedure or else use one of the other overloads for returning a dataset that does instiante the dataset for the calling code..
        /// </summary>
        public static string DataAccess_GetDataSet_The_method_did_not_receive_an_instianted_dataset__dataset_was_nothing___The_dataset_must_be_instianted_before_calling_this_procedure_or_else_use_one_of_the_other_overloads_for_returning_a_dataset_that_does_instiante_the_dataset_for_the_calling_code_ {
            get {
                return ResourceManager.GetString(@"DataAccess_GetDataSet_The_method_did_not_receive_an_instianted_dataset__dataset_was_nothing___The_dataset_must_be_instianted_before_calling_this_procedure_or_else_use_one_of_the_other_overloads_for_returning_a_dataset_that_does_instiante_the_dataset_for_the_calling_code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method did not receive any TableNames.  At least one table name must be supplied..
        /// </summary>
        public static string DataAccess_GetDataSet_The_method_did_not_receive_any_TableNames___At_least_one_table_name_must_be_supplied_ {
            get {
                return ResourceManager.GetString("DataAccess_GetDataSet_The_method_did_not_receive_any_TableNames___At_least_one_ta" +
                        "ble_name_must_be_supplied_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method did not receive an instianted dataset, datatable was nothing.  The datatable must be instianted before calling this procedure or else use one of the other overloads for returning a datatable that does instiante the datatable for the calling code..
        /// </summary>
        public static string DataAccess_GetDataTable_The_method_did_not_receive_an_instianted_dataset__datatable_was_nothing___The_datatable_must_be_instianted_before_calling_this_procedure_or_else_use_one_of_the_other_overloads_for_returning_a_datatable_that_does_instiante_the_datatable_for_the_calling_code_ {
            get {
                return ResourceManager.GetString(@"DataAccess_GetDataTable_The_method_did_not_receive_an_instianted_dataset__datatable_was_nothing___The_datatable_must_be_instianted_before_calling_this_procedure_or_else_use_one_of_the_other_overloads_for_returning_a_datatable_that_does_instiante_the_datatable_for_the_calling_code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method did not receive the TableName..
        /// </summary>
        public static string DataAccess_GetDataTable_The_method_did_not_receive_the_TableName_ {
            get {
                return ResourceManager.GetString("DataAccess_GetDataTable_The_method_did_not_receive_the_TableName_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While saving this record there was a violation of a database unique index.{0}{0}The system was unable to retrieve the column names.{0}{0}Please see your administrator for data entry help.{0}{0}.
        /// </summary>
        public static string DataAccess_ParseSqlClientExceptions_While_saving_this_record_there_was_a_violation_of_a_database_unique_index__0__0_The_system_was_unable_to_retrieve_the_column_names__0__0_Please_see_your_administrator_for_data_entry_help__0__0_FormatString {
            get {
                return ResourceManager.GetString("DataAccess_ParseSqlClientExceptions_While_saving_this_record_there_was_a_violatio" +
                        "n_of_a_database_unique_index__0__0_The_system_was_unable_to_retrieve_the_column_" +
                        "names__0__0_Please_see_your_administrator_for_data_entry_help__0__0_FormatString" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While saving this record there was a violation of a database unique index.{1}{1}The following field(s) make up the unique index {0}.{1}{1}Please see your administrator for data entry help..
        /// </summary>
        public static string DataAccess_ParseSqlClientExceptions_While_saving_this_record_there_was_a_violation_of_a_database_unique_index__1__1_The_following_field_s__make_up_the_unique_index__0___1__1_Please_see_your_administrator_for_data_entry_help_FormatString {
            get {
                return ResourceManager.GetString("DataAccess_ParseSqlClientExceptions_While_saving_this_record_there_was_a_violatio" +
                        "n_of_a_database_unique_index__1__1_The_following_field_s__make_up_the_unique_ind" +
                        "ex__0___1__1_Please_see_your_administrator_for_data_entry_help_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} was not found in the collection of connection strings..
        /// </summary>
        public static string DataAccessConnection_GetConnectionString_The__0__was_not_found_in_the_collection_of_connection_strings_FormatString {
            get {
                return ResourceManager.GetString("DataAccessConnection_GetConnectionString_The__0__was_not_found_in_the_collection_" +
                        "of_connection_strings_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse database name from connection string: {0}..
        /// </summary>
        public static string SqlConnectionStringAssistant_ParseDatabaseNameFromConnectionString_Could_not_parse_database_name_from_connection_string___0__FormatString {
            get {
                return ResourceManager.GetString("SqlConnectionStringAssistant_ParseDatabaseNameFromConnectionString_Could_not_pars" +
                        "e_database_name_from_connection_string___0__FormatString", resourceCulture);
            }
        }
    }
}
