//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ocean.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ocean.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey! The PART_IndicatorList is missing from the template or is not an ItemsControl.  Sorry but this ItemsControl is required..
        /// </summary>
        internal static string CheckListBox_OnApplyTemplate_Hey__The_PART_IndicatorList_is_missing_from_the_template_or_is_not_an_ItemsControl___Sorry_but_this_ItemsControl_is_required_ {
            get {
                return ResourceManager.GetString("CheckListBox_OnApplyTemplate_Hey__The_PART_IndicatorList_is_missing_from_the_temp" +
                        "late_or_is_not_an_ItemsControl___Sorry_but_this_ItemsControl_is_required_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid content. CheckListBox only accepts a ListBox control as its content..
        /// </summary>
        internal static string CheckListBox_OnContentChanged_Invalid_content__CheckListBox_only_accepts_a_ListBox_control_as_its_content_ {
            get {
                return ResourceManager.GetString("CheckListBox_OnContentChanged_Invalid_content__CheckListBox_only_accepts_a_ListBo" +
                        "x_control_as_its_content_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer did not program for this icon..
        /// </summary>
        internal static string CustomTaskDialog_GetIcon_Programmer_did_not_program_for_this_icon_ {
            get {
                return ResourceManager.GetString("CustomTaskDialog_GetIcon_Programmer_did_not_program_for_this_icon_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer did not program for this selection..
        /// </summary>
        internal static string CustomTaskDialog_SetButtons_Programmer_did_not_program_for_this_selection_ {
            get {
                return ResourceManager.GetString("CustomTaskDialog_SetButtons_Programmer_did_not_program_for_this_selection_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Details.
        /// </summary>
        internal static string CustomTaskDialogWindow_expAdditionalDetails_Collapsed_See_Details {
            get {
                return ResourceManager.GetString("CustomTaskDialogWindow_expAdditionalDetails_Collapsed_See_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Details.
        /// </summary>
        internal static string CustomTaskDialogWindow_expAdditionalDetails_Expanded_Hide_Details {
            get {
                return ResourceManager.GetString("CustomTaskDialogWindow_expAdditionalDetails_Expanded_Hide_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string DialogFacade_ExceptionDialog_Exception {
            get {
                return ResourceManager.GetString("DialogFacade_ExceptionDialog_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Save.
        /// </summary>
        internal static string DialogFacade_YesNoCancelConfirmSave_Confirm_Save {
            get {
                return ResourceManager.GetString("DialogFacade_YesNoCancelConfirmSave_Confirm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string DialogFacade_YesNoCancelConfirmSave_Save {
            get {
                return ResourceManager.GetString("DialogFacade_YesNoCancelConfirmSave_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your data before closing this form?.
        /// </summary>
        internal static string DialogFacade_YesNoCancelConfirmSave_Would_you_like_to_save_your_data_before_closing_this_form_ {
            get {
                return ResourceManager.GetString("DialogFacade_YesNoCancelConfirmSave_Would_you_like_to_save_your_data_before_closi" +
                        "ng_this_form_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this data?.
        /// </summary>
        internal static string DialogFacade_YesNoConfirmDelete_Are_you_sure_you_want_to_delete_this_data_ {
            get {
                return ResourceManager.GetString("DialogFacade_YesNoConfirmDelete_Are_you_sure_you_want_to_delete_this_data_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string DialogFacade_YesNoConfirmDelete_Confirm_Delete {
            get {
                return ResourceManager.GetString("DialogFacade_YesNoConfirmDelete_Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DialogFacade_YesNoConfirmDelete_Delete {
            get {
                return ResourceManager.GetString("DialogFacade_YesNoConfirmDelete_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attached behavior only works with UIElements.
        /// </summary>
        internal static string EnterKeyDownBehavior_EnterKeyDownChanged_This_attached_behavior_only_works_with_UIElements {
            get {
                return ResourceManager.GetString("EnterKeyDownBehavior_EnterKeyDownChanged_This_attached_behavior_only_works_with_U" +
                        "IElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attached behavior only works with UIElements.
        /// </summary>
        internal static string EscapeKeyDownBehavior_EscapeKeyDownChanged_This_attached_behavior_only_works_with_UIElements {
            get {
                return ResourceManager.GetString("EscapeKeyDownBehavior_EscapeKeyDownChanged_This_attached_behavior_only_works_with" +
                        "_UIElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attached behavior only works with UIElements.
        /// </summary>
        internal static string KeyDownBehavior_KeyDownChanged_This_attached_behavior_only_works_with_UIElements {
            get {
                return ResourceManager.GetString("KeyDownBehavior_KeyDownChanged_This_attached_behavior_only_works_with_UIElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey! The PART_IndicatorList is missing from the template or is not an ItemsControl.  Sorry but this ItemsControl is required..
        /// </summary>
        internal static string ListBoxWithSelectedItemIndicator_OnApplyTemplate_Hey__The_PART_IndicatorList_is_missing_from_the_template_or_is_not_an_ItemsControl___Sorry_but_this_ItemsControl_is_required_ {
            get {
                return ResourceManager.GetString("ListBoxWithSelectedItemIndicator_OnApplyTemplate_Hey__The_PART_IndicatorList_is_m" +
                        "issing_from_the_template_or_is_not_an_ItemsControl___Sorry_but_this_ItemsControl" +
                        "_is_required_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid content. ListBoxWithSelectedItemIndicator only accepts a ListBox control as its content..
        /// </summary>
        internal static string ListBoxWithSelectedItemIndicator_OnContentChanged_Invalid_content__ListBoxWithSelectedItemIndicator_only_accepts_a_ListBox_control_as_its_content_ {
            get {
                return ResourceManager.GetString("ListBoxWithSelectedItemIndicator_OnContentChanged_Invalid_content__ListBoxWithSel" +
                        "ectedItemIndicator_only_accepts_a_ListBox_control_as_its_content_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File To Open.
        /// </summary>
        internal static string OpenFileDialog__title_Select_File_To_Open {
            get {
                return ResourceManager.GetString("OpenFileDialog__title_Select_File_To_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate comamnds can not be null.
        /// </summary>
        internal static string RelayCommand_RelayCommand_Delegate_comamnds_can_not_be_null {
            get {
                return ResourceManager.GetString("RelayCommand_RelayCommand_Delegate_comamnds_can_not_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File To Save.
        /// </summary>
        internal static string SaveFileDialog__title_Select_File_To_Save {
            get {
                return ResourceManager.GetString("SaveFileDialog__title_Select_File_To_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date is not a valid format..
        /// </summary>
        internal static string UIValidationError_ToFriendlyErrorMessage_date_is_not_a_valid_format_ {
            get {
                return ResourceManager.GetString("UIValidationError_ToFriendlyErrorMessage_date_is_not_a_valid_format_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entered value is not the correct data type..
        /// </summary>
        internal static string UIValidationError_ToFriendlyErrorMessage_entered_value_is_not_the_correct_data_type_ {
            get {
                return ResourceManager.GetString("UIValidationError_ToFriendlyErrorMessage_entered_value_is_not_the_correct_data_ty" +
                        "pe_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataItem: {0}, PropertyName: {1}, Error: {2}.
        /// </summary>
        internal static string UIValidationError_ToString_DataItem___0___PropertyName___1___Error___2_FormatString {
            get {
                return ResourceManager.GetString("UIValidationError_ToString_DataItem___0___PropertyName___1___Error___2_FormatStri" +
                        "ng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Window must be shown before extending glass..
        /// </summary>
        internal static string VistaAeroAPI_ExtendGlassFrame_The_Window_must_be_shown_before_extending_glass_ {
            get {
                return ResourceManager.GetString("VistaAeroAPI_ExtendGlassFrame_The_Window_must_be_shown_before_extending_glass_", resourceCulture);
            }
        }
    }
}
