//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ocean.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ocean.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndLoading never called after a BeginLoading call was made.  No operations are permitted until EndLoading has been called..
        /// </summary>
        public static string BusinessEntityBase_STRING_END_LOADING_NEVER_CALLED_EndLoading_never_called_after_a_BeginLoading_call_was_made___No_operations_are_permitted_until_EndLoading_has_been_called_ {
            get {
                return ResourceManager.GetString("BusinessEntityBase_STRING_END_LOADING_NEVER_CALLED_EndLoading_never_called_after_" +
                        "a_BeginLoading_call_was_made___No_operations_are_permitted_until_EndLoading_has_" +
                        "been_called_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LookFor and ReplaceWith strings must be the same length..
        /// </summary>
        public static string CharacterCasingCheck_CharacterCasingCheck_The_LookFor_and_ReplaceWith_strings_must_be_the_same_length_ {
            get {
                return ResourceManager.GetString("CharacterCasingCheck_CharacterCasingCheck_The_LookFor_and_ReplaceWith_strings_mus" +
                        "t_be_the_same_length_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look For and Replace With must be the same length..
        /// </summary>
        public static string CharacterCasingCheck_Error_Look_For_and_Replace_With_must_be_the_same_length_ {
            get {
                return ResourceManager.GetString("CharacterCasingCheck_Error_Look_For_and_Replace_With_must_be_the_same_length_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look For is a required field..
        /// </summary>
        public static string CharacterCasingCheck_Error_Look_For_is_a_required_field_ {
            get {
                return ResourceManager.GetString("CharacterCasingCheck_Error_Look_For_is_a_required_field_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace With is a required field..
        /// </summary>
        public static string CharacterCasingCheck_Error_Replace_With_is_a_required_field_ {
            get {
                return ResourceManager.GetString("CharacterCasingCheck_Error_Replace_With_is_a_required_field_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class has no properties.
        /// </summary>
        public static string ClassMessageCreationHelper_ClassToString_Class_has_no_properties {
            get {
                return ResourceManager.GetString("ClassMessageCreationHelper_ClassToString_Class_has_no_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ConvertToType has not yet been programmed, value passed was: {0}.
        /// </summary>
        public static string CompareValueValidatorAttribute_CompareValueValidatorAttribute_This_ConvertToType_has_not_yet_been_programmed__value_passed_was___0_FomatString {
            get {
                return ResourceManager.GetString("CompareValueValidatorAttribute_CompareValueValidatorAttribute_This_ConvertToType_" +
                        "has_not_yet_been_programmed__value_passed_was___0_FomatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equal to {1}..
        /// </summary>
        public static string ComparisonValidationRules_ComparePropertyRule__0__must_be_equal_to__1__FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_ComparePropertyRule__0__must_be_equal_to__1__FormatStri" +
                        "ng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string ComparisonValidationRules_ComparePropertyRule__0__must_be_greater_than__1__FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_ComparePropertyRule__0__must_be_greater_than__1__Format" +
                        "String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        public static string ComparisonValidationRules_ComparePropertyRule__0__must_be_greater_than_or_equal_to__1__FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_ComparePropertyRule__0__must_be_greater_than_or_equal_t" +
                        "o__1__FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        public static string ComparisonValidationRules_ComparePropertyRule__0__must_be_less_than__1__FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_ComparePropertyRule__0__must_be_less_than__1__FormatStr" +
                        "ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}..
        /// </summary>
        public static string ComparisonValidationRules_ComparePropertyRule__0__must_be_less_than_or_equal_to__1__FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_ComparePropertyRule__0__must_be_less_than_or_equal_to__" +
                        "1__FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not equal {1}..
        /// </summary>
        public static string ComparisonValidationRules_ComparePropertyRule__0__must_not_equal__1__FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_ComparePropertyRule__0__must_not_equal__1__FormatString" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was null or empty but is a required field..
        /// </summary>
        public static string ComparisonValidationRules_ComparePropertyRule__0__was_null_or_empty_but_is_a_required_field_FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_ComparePropertyRule__0__was_null_or_empty_but_is_a_requ" +
                        "ired_field_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparision type not programmed.
        /// </summary>
        public static string ComparisonValidationRules_ComparePropertyRule_Comparision_type_not_programmed {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_ComparePropertyRule_Comparision_type_not_programmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong rule passed to ComparePropertyRule: {0}.
        /// </summary>
        public static string ComparisonValidationRules_ComparePropertyRule_Wrong_rule_passed_to_ComparePropertyRule_FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_ComparePropertyRule_Wrong_rule_passed_to_ComparePropert" +
                        "yRule_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong rule passed to CompareValueRule: {0}.
        /// </summary>
        public static string ComparisonValidationRules_CompareValueRule_Wrong_rule_passed_to_CompareValueRule___0_FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_CompareValueRule_Wrong_rule_passed_to_CompareValueRule_" +
                        "__0_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}.
        /// </summary>
        public static string ComparisonValidationRules_InRangeRule__0__must_be_greater_than__1_FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_InRangeRule__0__must_be_greater_than__1_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}.
        /// </summary>
        public static string ComparisonValidationRules_InRangeRule__0__must_be_greater_than_or_equal_to__1_FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_InRangeRule__0__must_be_greater_than_or_equal_to__1_For" +
                        "matString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}.
        /// </summary>
        public static string ComparisonValidationRules_InRangeRule__0__must_be_less_than__1_FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_InRangeRule__0__must_be_less_than__1_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}.
        /// </summary>
        public static string ComparisonValidationRules_InRangeRule__0__must_be_less_than_or_equal_to__1_FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_InRangeRule__0__must_be_less_than_or_equal_to__1_Format" +
                        "String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong rule passed to InRangeRule: {0}.
        /// </summary>
        public static string ComparisonValidationRules_InRangeRule_Wrong_rule_passed_to_InRangeRule___0_FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_InRangeRule_Wrong_rule_passed_to_InRangeRule___0_Format" +
                        "String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is DBNull..
        /// </summary>
        public static string ComparisonValidationRules_NotNullRule__0__is_DBNull_FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_NotNullRule__0__is_DBNull_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null..
        /// </summary>
        public static string ComparisonValidationRules_NotNullRule__0__is_null_FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_NotNullRule__0__is_null_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong rule passed to NotNullRule: {0}.
        /// </summary>
        public static string ComparisonValidationRules_NotNullRule_Wrong_rule_passed_to_NotNullRule___0_FormatString {
            get {
                return ResourceManager.GetString("ComparisonValidationRules_NotNullRule_Wrong_rule_passed_to_NotNullRule___0_Format" +
                        "String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method did not receive any command text.  Calling code must supply the command text..
        /// </summary>
        public static string DataAccess_ExecuteNonQuery_The_method_did_not_receive_any_command_text___Calling_code_must_supply_the_command_text_ {
            get {
                return ResourceManager.GetString("DataAccess_ExecuteNonQuery_The_method_did_not_receive_any_command_text___Calling_" +
                        "code_must_supply_the_command_text_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sqlconnection state was {0}.  The method only permits the sqlconnection state to be either open or closed only..
        /// </summary>
        public static string DataAccess_ExecuteNonQuery_The_sqlconnection_state_was__0____The_method_only_permits_the_sqlconnection_state_to_be_either_open_or_closed_only_FormatString {
            get {
                return ResourceManager.GetString("DataAccess_ExecuteNonQuery_The_sqlconnection_state_was__0____The_method_only_perm" +
                        "its_the_sqlconnection_state_to_be_either_open_or_closed_only_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer did not program this value..
        /// </summary>
        public static string DataGenerator_GetString_Programmer_did_not_program_this_value_ {
            get {
                return ResourceManager.GetString("DataGenerator_GetString_Programmer_did_not_program_this_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} did not match any of the following acceptable values.
        /// </summary>
        public static string DomainValidationRules_DomainRule_The__0__did_not_match_any_of_the_following_acceptable_values_FormatString {
            get {
                return ResourceManager.GetString("DomainValidationRules_DomainRule_The__0__did_not_match_any_of_the_following_accep" +
                        "table_values_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong rule passed to DomainRule: {0}.
        /// </summary>
        public static string DomainValidationRules_DomainRule_Wrong_rule_passed_to_DomainRule___0_FormatString {
            get {
                return ResourceManager.GetString("DomainValidationRules_DomainRule_Wrong_rule_passed_to_DomainRule___0_FormatString" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndLoading never called after a BeginLoading call was made.  No operations are permitted until EndLoading has been called..
        /// </summary>
        public static string EndLoadingNotCalled {
            get {
                return ResourceManager.GetString("EndLoadingNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression is not a member access expression..
        /// </summary>
        public static string PropertySupport_ExtractPropertyName_The_expression_is_not_a_member_access_expression_ {
            get {
                return ResourceManager.GetString("PropertySupport_ExtractPropertyName_The_expression_is_not_a_member_access_express" +
                        "ion_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member access expression does not access a property..
        /// </summary>
        public static string PropertySupport_ExtractPropertyName_The_member_access_expression_does_not_access_a_property_ {
            get {
                return ResourceManager.GetString("PropertySupport_ExtractPropertyName_The_member_access_expression_does_not_access_" +
                        "a_property_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced property is a static property..
        /// </summary>
        public static string PropertySupport_ExtractPropertyName_The_referenced_property_is_a_static_property_ {
            get {
                return ResourceManager.GetString("PropertySupport_ExtractPropertyName_The_referenced_property_is_a_static_property_" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tryagain.
        /// </summary>
        public static string RandomPassword_Generate_tryagain {
            get {
                return ResourceManager.GetString("RandomPassword_Generate_tryagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ConvertToType has not yet been programmed, value passed was: {0}.
        /// </summary>
        public static string RangeValidatorAttribute_RangeValidatorAttribute_This_ConvertToType_has_not_yet_been_programmed__value_passed_was___0_FormatString {
            get {
                return ResourceManager.GetString("RangeValidatorAttribute_RangeValidatorAttribute_This_ConvertToType_has_not_yet_be" +
                        "en_programmed__value_passed_was___0_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before setting a custom pattern, the Pattern Type must be custom..
        /// </summary>
        public static string RegularExpressionRuleDescriptor_CustomRegularExpressionPattern_Before_setting_a_custom_pattern__the_Pattern_Type_must_be_custom_ {
            get {
                return ResourceManager.GetString("RegularExpressionRuleDescriptor_CustomRegularExpressionPattern_Before_setting_a_c" +
                        "ustom_pattern__the_Pattern_Type_must_be_custom_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is not a valid regular expression..
        /// </summary>
        public static string RegularExpressionRuleDescriptor_CustomRegularExpressionPattern_value_is_not_a_valid_regular_expression_ {
            get {
                return ResourceManager.GetString("RegularExpressionRuleDescriptor_CustomRegularExpressionPattern_value_is_not_a_val" +
                        "id_regular_expression_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This constructor does not support assigning the RegularExpressionPatternType to Custom.  Use other constructor..
        /// </summary>
        public static string RegularExpressionRuleDescriptor_RegularExpressionRuleDescriptor_This_constructor_does_not_support_assigning_the_RegularExpressionPatternType_to_Custom___Use_other_constructor_ {
            get {
                return ResourceManager.GetString("RegularExpressionRuleDescriptor_RegularExpressionRuleDescriptor_This_constructor_" +
                        "does_not_support_assigning_the_RegularExpressionPatternType_to_Custom___Use_othe" +
                        "r_constructor_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer did not supply a valid CustomRegularExpressionPattern.
        /// </summary>
        public static string RegularExpressionValidatorAttribute_RegularExpressionValidatorAttribute_Programmer_did_not_supply_a_valid_CustomRegularExpressionPattern {
            get {
                return ResourceManager.GetString("RegularExpressionValidatorAttribute_RegularExpressionValidatorAttribute_Programme" +
                        "r_did_not_supply_a_valid_CustomRegularExpressionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Broken Rule Description For {0}.
        /// </summary>
        public static string RuleDescriptorBase_BrokenRuleDescription_Missing_Broken_Rule_Description_For_FormatString {
            get {
                return ResourceManager.GetString("RuleDescriptorBase_BrokenRuleDescription_Missing_Broken_Rule_Description_For_Form" +
                        "atString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State abbreviation: {0}, is not valid.
        /// </summary>
        public static string StateAbbreviationValidator_GetStateName_State_abbreviation___0___is_not_valid_FormatString {
            get {
                return ResourceManager.GetString("StateAbbreviationValidator_GetStateName_State_abbreviation___0___is_not_valid_For" +
                        "matString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be greater than 0..
        /// </summary>
        public static string StringLengthRuleDescriptor_StringLengthRuleDescriptor_must_be_greater_than_0_ {
            get {
                return ResourceManager.GetString("StringLengthRuleDescriptor_StringLengthRuleDescriptor_must_be_greater_than_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be greater than or equal to the MinimumLength..
        /// </summary>
        public static string StringLengthRuleDescriptor_StringLengthRuleDescriptor_must_be_greater_than_or_equal_to_the_MinimumLength_ {
            get {
                return ResourceManager.GetString("StringLengthRuleDescriptor_StringLengthRuleDescriptor_must_be_greater_than_or_equ" +
                        "al_to_the_MinimumLength_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be greater than 0..
        /// </summary>
        public static string StringLengthValidatorAttribute_StringLengthValidatorAttribute_must_be_greater_than_0_ {
            get {
                return ResourceManager.GetString("StringLengthValidatorAttribute_StringLengthValidatorAttribute_must_be_greater_tha" +
                        "n_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must be greater than or equal to the MinimumLength..
        /// </summary>
        public static string StringLengthValidatorAttribute_StringLengthValidatorAttribute_must_be_greater_than_or_equal_to_the_MinimumLength_ {
            get {
                return ResourceManager.GetString("StringLengthValidatorAttribute_StringLengthValidatorAttribute_must_be_greater_tha" +
                        "n_or_equal_to_the_MinimumLength_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was null or empty but is a required field..
        /// </summary>
        public static string StringValidationRules_BankRoutingNumberRule__0__was_null_or_empty_but_is_a_required_field_ {
            get {
                return ResourceManager.GetString("StringValidationRules_BankRoutingNumberRule__0__was_null_or_empty_but_is_a_requir" +
                        "ed_field_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank routing number validation rule can only be applied to String properties..
        /// </summary>
        public static string StringValidationRules_BankRoutingNumberRule_Bank_routing_number_validation_rule_can_only_be_applied_to_String_properties_ {
            get {
                return ResourceManager.GetString("StringValidationRules_BankRoutingNumberRule_Bank_routing_number_validation_rule_c" +
                        "an_only_be_applied_to_String_properties_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered value {0} is not a valid bank routing number.  All bank routing numbers are 9 digits in length..
        /// </summary>
        public static string StringValidationRules_BankRoutingNumberRule_The_entered_value__0__is_not_a_valid_bank_routing_number___All_bank_routing_numbers_are_9_digits_in_length_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_BankRoutingNumberRule_The_entered_value__0__is_not_a_valid_" +
                        "bank_routing_number___All_bank_routing_numbers_are_9_digits_in_length_FormatStri" +
                        "ng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered value {0} is not a valid bank routing number.  Only numeric input is allowed..
        /// </summary>
        public static string StringValidationRules_BankRoutingNumberRule_The_entered_value__0__is_not_a_valid_bank_routing_number___Only_numeric_input_is_allowed_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_BankRoutingNumberRule_The_entered_value__0__is_not_a_valid_" +
                        "bank_routing_number___Only_numeric_input_is_allowed_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered value {0} is not a valid bank routing number.  The first digit must be a 0 or a 1..
        /// </summary>
        public static string StringValidationRules_BankRoutingNumberRule_The_entered_value__0__is_not_a_valid_bank_routing_number___The_first_digit_must_be_a_0_or_a_1_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_BankRoutingNumberRule_The_entered_value__0__is_not_a_valid_" +
                        "bank_routing_number___The_first_digit_must_be_a_0_or_a_1_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered value {0} is not a valid bank routing number..
        /// </summary>
        public static string StringValidationRules_BankRoutingNumberRule_The_entered_value__0__is_not_a_valid_bank_routing_number_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_BankRoutingNumberRule_The_entered_value__0__is_not_a_valid_" +
                        "bank_routing_number_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong rule passed to BankRoutingNumberRule: {0}.
        /// </summary>
        public static string StringValidationRules_BankRoutingNumberRule_Wrong_rule_passed_to_BankRoutingNumberRule_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_BankRoutingNumberRule_Wrong_rule_passed_to_BankRoutingNumbe" +
                        "rRule_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card number validation rule can only be applied to String properties..
        /// </summary>
        public static string StringValidationRules_CreditCardNumberRule_Credit_card_number_validation_rule_can_only_be_applied_to_String_properties_ {
            get {
                return ResourceManager.GetString("StringValidationRules_CreditCardNumberRule_Credit_card_number_validation_rule_can" +
                        "_only_be_applied_to_String_properties_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered value {0} is not a valid credit card number.  Only numeric input is allowed..
        /// </summary>
        public static string StringValidationRules_CreditCardNumberRule_The_entered_value__0__is_not_a_valid_credit_card_number___Only_numeric_input_is_allowed_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_CreditCardNumberRule_The_entered_value__0__is_not_a_valid_c" +
                        "redit_card_number___Only_numeric_input_is_allowed_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered value {0} is not a valid credit card number..
        /// </summary>
        public static string StringValidationRules_CreditCardNumberRule_The_entered_value__0__is_not_a_valid_credit_card_number_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_CreditCardNumberRule_The_entered_value__0__is_not_a_valid_c" +
                        "redit_card_number_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong rule passed to CreditCardNumberRule: {0}.
        /// </summary>
        public static string StringValidationRules_CreditCardNumberRule_Wrong_rule_passed_to_CreditCardNumberRule___0_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_CreditCardNumberRule_Wrong_rule_passed_to_CreditCardNumberR" +
                        "ule___0_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not match the required {1} pattern..
        /// </summary>
        public static string StringValidationRules_RegularExpressionRule__0__did_not_match_the_required__1__pattern_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_RegularExpressionRule__0__did_not_match_the_required__1__pa" +
                        "ttern_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not match the required email pattern..
        /// </summary>
        public static string StringValidationRules_RegularExpressionRule__0__did_not_match_the_required_email_pattern_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_RegularExpressionRule__0__did_not_match_the_required_email_" +
                        "pattern_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not match the required IP Address pattern..
        /// </summary>
        public static string StringValidationRules_RegularExpressionRule__0__did_not_match_the_required_IP_Address_pattern_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_RegularExpressionRule__0__did_not_match_the_required_IP_Add" +
                        "ress_pattern_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not match the required SSN pattern..
        /// </summary>
        public static string StringValidationRules_RegularExpressionRule__0__did_not_match_the_required_SSN_pattern_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_RegularExpressionRule__0__did_not_match_the_required_SSN_pa" +
                        "ttern_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not match the required URL pattern..
        /// </summary>
        public static string StringValidationRules_RegularExpressionRule__0__did_not_match_the_required_URL_pattern_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_RegularExpressionRule__0__did_not_match_the_required_URL_pa" +
                        "ttern_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not match the required Zip Code pattern..
        /// </summary>
        public static string StringValidationRules_RegularExpressionRule__0__did_not_match_the_required_Zip_Code_pattern_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_RegularExpressionRule__0__did_not_match_the_required_Zip_Co" +
                        "de_pattern_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomRegularExpressionPattern not supplied.
        /// </summary>
        public static string StringValidationRules_RegularExpressionRule_CustomRegularExpressionPattern_not_supplied {
            get {
                return ResourceManager.GetString("StringValidationRules_RegularExpressionRule_CustomRegularExpressionPattern_not_su" +
                        "pplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmer did not program this RegularExpressionPatternType.
        /// </summary>
        public static string StringValidationRules_RegularExpressionRule_Programmer_did_not_program_this_RegularExpressionPatternType {
            get {
                return ResourceManager.GetString("StringValidationRules_RegularExpressionRule_Programmer_did_not_program_this_Regul" +
                        "arExpressionPatternType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong rule passed to RegularExpressionRule: {0}.
        /// </summary>
        public static string StringValidationRules_RegularExpressionRule_Wrong_rule_passed_to_RegularExpressionRule___0_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_RegularExpressionRule_Wrong_rule_passed_to_RegularExpressio" +
                        "nRule___0_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State abbreviation validation rule can only be applied to String properties..
        /// </summary>
        public static string StringValidationRules_StateAbbreviationRule_State_abbreviation_validation_rule_can_only_be_applied_to_String_properties_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_StateAbbreviationRule_State_abbreviation_validation_rule_ca" +
                        "n_only_be_applied_to_String_properties_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered value {0} is not a valid state abbreviation..
        /// </summary>
        public static string StringValidationRules_StateAbbreviationRule_The_entered_value__0__is_not_a_valid_state_abbreviation_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_StateAbbreviationRule_The_entered_value__0__is_not_a_valid_" +
                        "state_abbreviation_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong rule passed to StateAbbreviationRule: {0}.
        /// </summary>
        public static string StringValidationRules_StateAbbreviationRule_Wrong_rule_passed_to_StateAbbreviationRule___0_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_StateAbbreviationRule_Wrong_rule_passed_to_StateAbbreviatio" +
                        "nRule___0_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be greater than {1} character(s) long..
        /// </summary>
        public static string StringValidationRules_StringLengthRule__0__can_not_be_greater_than__1__character_s__long_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_StringLengthRule__0__can_not_be_greater_than__1__character_" +
                        "s__long_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be less than {1} character(s) long..
        /// </summary>
        public static string StringValidationRules_StringLengthRule__0__can_not_be_less_than__1__character_s__long_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_StringLengthRule__0__can_not_be_less_than__1__character_s__" +
                        "long_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be null..
        /// </summary>
        public static string StringValidationRules_StringLengthRule__0__can_not_be_null_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_StringLengthRule__0__can_not_be_null_FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong rule passed to StringLengthRule: {0}.
        /// </summary>
        public static string StringValidationRules_StringLengthRule_Wrong_rule_passed_to_StringLengthRule___0_FormatString {
            get {
                return ResourceManager.GetString("StringValidationRules_StringLengthRule_Wrong_rule_passed_to_StringLengthRule___0_" +
                        "FormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleType not programmed yet.
        /// </summary>
        public static string Validator_Validator_RuleType_not_programmed_yet {
            get {
                return ResourceManager.GetString("Validator_Validator_RuleType_not_programmed_yet", resourceCulture);
            }
        }
    }
}
