//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using TiendaVirtual.Domain;

namespace TiendaVirtual.Persistence
{
    public partial class DataContext : ObjectContext
    {
        public const string ConnectionString = "name=DataContext";
        public const string ContainerName = "DataContext";
    
        #region Constructors
    
        public DataContext()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public DataContext(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public DataContext(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Producto> Productos
        {
            get { return _productos  ?? (_productos = CreateObjectSet<Producto>("Productos")); }
        }
        private ObjectSet<Producto> _productos;
    
        public ObjectSet<Categoria> Categorias
        {
            get { return _categorias  ?? (_categorias = CreateObjectSet<Categoria>("Categorias")); }
        }
        private ObjectSet<Categoria> _categorias;

        #endregion
    }
}
